name: Release APKs

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0, v2.0.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Android SDK
        uses: android-actions/setup-android@v2

      - name: Decode Keystore File
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" > hackerbuzz-release.keystore.base64
          base64 --decode hackerbuzz-release.keystore.base64 > android/app/hackerbuzz-release.keystore

      - name: Verify Keystore File
        run: |
          ls -la android/app/hackerbuzz-release.keystore
          keytool -list -v -keystore android/app/hackerbuzz-release.keystore -storepass ${{ secrets.MYAPP_UPLOAD_STORE_PASSWORD }}

      - name: Build APKs
        run: |
          cd android
          ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_FILE=hackerbuzz-release.keystore -PMYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.MYAPP_UPLOAD_STORE_PASSWORD }} -PMYAPP_UPLOAD_KEY_ALIAS=${{ secrets.MYAPP_UPLOAD_KEY_ALIAS }} -PMYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}

      - name: List APK Files
        run: |
          ls -la android/app/build/outputs/apk/release/

      - name: Upload APKs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: |
            android/app/build/outputs/apk/release/*.apk

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APKs
        uses: actions/download-artifact@v4
        with:
          name: apks
          path: ./apks
      
      - name: Set APK path variables
        id: set-apk-paths
        run: |
          echo "universal_apk=$(find ./apks -name '*universal*.apk' -type f)" >> $GITHUB_OUTPUT
          echo "armeabi_apk=$(find ./apks -name '*armeabi-v7a*.apk' -type f)" >> $GITHUB_OUTPUT
          echo "arm64_apk=$(find ./apks -name '*arm64-v8a*.apk' -type f)" >> $GITHUB_OUTPUT
          echo "x86_apk=$(find ./apks -name '*x86[^_]*.apk' -type f)" >> $GITHUB_OUTPUT
          echo "x86_64_apk=$(find ./apks -name '*x86_64*.apk' -type f)" >> $GITHUB_OUTPUT
  
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  
      - name: Upload Universal APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.set-apk-paths.outputs.universal_apk }}
          asset_name: hackerbuzz-release-universal.apk
          asset_content_type: application/vnd.android.package-archive
  
      - name: Upload armeabi-v7a APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.set-apk-paths.outputs.armeabi_apk }}
          asset_name: hackerbuzz-release-armeabi-v7a.apk
          asset_content_type: application/vnd.android.package-archive
  
      - name: Upload arm64-v8a APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.set-apk-paths.outputs.arm64_apk }}
          asset_name: hackerbuzz-release-arm64-v8a.apk
          asset_content_type: application/vnd.android.package-archive
  
      - name: Upload x86 APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.set-apk-paths.outputs.x86_apk }}
          asset_name: hackerbuzz-release-x86.apk
          asset_content_type: application/vnd.android.package-archive
  
      - name: Upload x86_64 APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.set-apk-paths.outputs.x86_64_apk }}
          asset_name: hackerbuzz-release-x86_64.apk
          asset_content_type: application/vnd.android.package-archive