name: Release APKs

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0, v2.0.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Android SDK
        uses: android-actions/setup-android@v2

      - name: Decode Keystore File
        run: |
          echo "${{ secrets.MYAPP_UPLOAD_STORE_FILE }}" > hackerbuzz-release.keystore.base64
          base64 --decode hackerbuzz-release.keystore.base64 > android/app/hackerbuzz-release.keystore

      - name: Build APKs
        run: |
          cd android
          ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_FILE=android/app/hackerbuzz-release.keystore -PMYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.MYAPP_UPLOAD_STORE_PASSWORD }} -PMYAPP_UPLOAD_KEY_ALIAS=${{ secrets.MYAPP_UPLOAD_KEY_ALIAS }} -PMYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}

      - name: Upload APKs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: |
            android/app/build/outputs/apk/release/hackerbuzz-release-universal-*.apk
            android/app/build/outputs/apk/release/hackerbuzz-release-armeabi-v7a-*.apk
            android/app/build/outputs/apk/release/hackerbuzz-release-arm64-v8a-*.apk
            android/app/build/outputs/apk/release/hackerbuzz-release-x86-*.apk
            android/app/build/outputs/apk/release/hackerbuzz-release-x86_64-*.apk

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APKs
        uses: actions/download-artifact@v4
        with:
          name: apks
          path: ./apks

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Universal APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./apks/hackerbuzz-release-universal-*.apk
          asset_name: hackerbuzz-release-universal.apk
          asset_content_type: application/zip

      - name: Upload armeabi-v7a APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./apks/hackerbuzz-release-armeabi-v7a-*.apk
          asset_name: hackerbuzz-release-armeabi-v7a.apk
          asset_content_type: application/zip

      - name: Upload arm64-v8a APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./apks/hackerbuzz-release-arm64-v8a-*.apk
          asset_name: hackerbuzz-release-arm64-v8a.apk
          asset_content_type: application/zip

      - name: Upload x86 APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./apks/hackerbuzz-release-x86-*.apk
          asset_name: hackerbuzz-release-x86.apk
          asset_content_type: application/zip

      - name: Upload x86_64 APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./apks/hackerbuzz-release-x86_64-*.apk
          asset_name: hackerbuzz-release-x86_64.apk
          asset_content_type: application/zip
